use_frameworks!

target 'INSBarcodeRFIDScanner_Example' do
    #pod 'INSBarcodeRFIDScanner', :path => '../'
    #pod 'INSBarcodeRFIDScanner', :path => '../'
    pod 'ZXingObjC'
    #pod 'INSBarcodeRFIDScanner', :git => 'https://PhucBui88@bitbucket.org/PhucBui88/insbarcoderfidscanner.git', :tag => ‘1.0.4’
    pod 'INSBarcodeRFIDScanner', :git => 'https://github.com/vanphuc06t1/INSBarcodeRFIDScanner.git', :branch => 'master'
 
#  target 'INSBarcodeRFIDScanner_Tests' do
#    inherit! :search_paths
#    pod 'ZXingObjC'
#    pod 'FBSnapshotTestCase'
#  end
end
